### ISSUE TITLE
Corrigir bug na listagem de Viagens ao realizar Busca

### ISSUE THREAD

**Issue by GabrielArSouza** [victoragnez/DataLAE#72]
Quando entramos em viagens no DataLae é lista ó nome da Área e Projeto corretamente. Quando vamos realizar uma busca não aparece nem a área, nem o projeto. Aparentemente não é montado os objetos corretamente

**Comment by victoragnez** [comment]
DataLae?

**Comment by GabrielArSouza** [comment]
isso o DataLAE, não sei se repete nas outras aplicações
